### ISSUE TITLE
 Stata factors to R factors

### ISSUE THREAD

**Issue by shv38339** [sjewo/readstata13#13]
Hello, I've used your package for a class I am assisting a professor with this semester and it has been very useful, but I have run into an issue.

I am importing a Stata 13 data set to R. I'm not too familiar with this Stata data set, but what I do know is that it has many factored variables WITH labels.

Unfortunately, I cannot figure out a way to upload the data set as factored but WITHOUT labels. I've played around with the options `convert.factors` and `generate.factors`, but I believe I am stuck. 

Thanks for taking the time to read this,
Steele
p.s. I searched around stackexchange/overflow but could not find an answer.

**Comment by sjewo** [comment]
At the moment there is no option to import factors without their labels, but you can easily convert them after import:

```
library(readstata13)

dat <- read.dta13(system.file("extdata/statacar.dta", package="readstata13"), convert.factors = F)

# identify variables with assigned labels
factorvars <- attr(dat,"val.label")!=""

# iterate over factors and convert
for(i in names(dat)[factorvars]) {
  dat[,i] <- as.factor(dat[,i])
}
```

**Comment by shv38339** [comment]
Thank you very much for the swift response. I'll be sure to let let me class know and keep up the great work.
