### ISSUE TITLE
Error saving dta

### ISSUE THREAD

**Issue by kendonB** [sjewo/readstata13#17]
Seems to work fine with iris but gives an error with this one.

My data:

https://www.dropbox.com/s/133i7pn7x0xcsj1/tmp.RData?dl=0

    save.dta13(data = tmp2, version = 117, file = "tmp.dta")
    #  Error in FUN(X[[i]], ...) : 
    # 4 arguments passed to .Internal(nchar) which requires 3

**Comment by kendonB** [comment]
This happens when trying to save a ``data.frame`` with ``character`` variables. Converting these to ``factor`` then allows it to work.

**Comment by JanMarvin** [comment]
Hey,
looked into it, works for me with the current CRAN release. Works with R and looks good in Stata 14. Anything I should look out for?

```R
> load("~/tmp.RData")
> 
> # install.packages("readstata13")
> library("readstata13")
> 
> save.dta13(data=tmp2, version=117, file="~/tmp2.dta")
> 
> dat <- read.dta13("~/tmp2.dta")
> any(unlist( Map(identical, tmp2, dat) ))
[1] TRUE
```

**Comment by JanMarvin** [comment]
Sorry, ment `all()` not `any()`
```R
> all(unlist( Map(identical, tmp2, dat) ))
[1] TRUE
```

**Comment by kendonB** [comment]
Strange. I'm using v0.7 (current on CRAN). Could be a Windows quirk? I'm also using RRO 3.2.0.

**Comment by JanMarvin** [comment]
Sorry, still unable to reproduce it (Windows 7 64bit and R 3.2.1 32- and 64-bit). RRO is built with the intel compiler icc iirc? That should not bother the CRAN Windows binary.

```R
> library("readstata13")
> load("C:/Temp/tmp.RData")
> save.dta13(data=tmp2, version=117, file="C:/Temp/tmp2.dta")
> dat <- read.dta13("C:/Temp/tmp2.dta")
> all(unlist( Map(identical, tmp2, dat) ))
[1] TRUE
```

**Comment by kendonB** [comment]
OK I have it working now. Had to upgrade to RRO 3.2.1. Thanks!

**Comment by JanMarvin** [comment]
No problem. Glad it is working.
