### ISSUE TITLE
Factors saving as numeric

### ISSUE THREAD

**Issue by kendonB** [sjewo/readstata13#23]
These I would expect to be the same:

    library(readstata13)
    save.dta13(iris, file = "iris.dta")
    tmp <- read.dta13("iris.dta")
    tmp$Species
    iris$Species

I'm sure this is a feature not a bug, but I'd give a warning that the factors don't save as strings:

**Comment by sjewo** [comment]
Hi Kendon,
factors are kept as integers by default. Please try this code:
```
library(readstata13)
save.dta13(iris, file = "iris.dta", convert.factors=T)
tmp <- read.dta13("iris.dta")
tmp$Species
iris$Species
```

**Comment by kendonB** [comment]
Seems to not work for large datasets:

    library(readstata13)
    iris_big <- bind_rows(lapply(1:1000, function(x) iris))
    save.dta13(iris_big, file = "iris_big.dta", convert.factors=T)
    tmp <- read.dta13("iris_big.dta")
    tmp$Species # All empty strings
    iris_big$Species # Good

**Comment by sjewo** [comment]
Works for me with R 3.2.2 on Windows 7 64bit and R 3.2.1on Linux 64bit with the package from CRAN. 

Can you give me some information about your OS and R version?

**Comment by kendonB** [comment]
I'm using RRO 3.2.1 on Windows 8.1 and readstata13_0.7.

**Comment by sjewo** [comment]
Please install the last version from CRAN (0.8) and try again.

**Comment by JanMarvin** [comment]
Works for me as well with Arch and our CRAN release. Sorry @kendonB but we do not use RRO and we do not develop for it. If you stick with them you are on your own. For issues, please test with R and the current CRAN release or our master branch.

**Comment by kendonB** [comment]
Works after upgrading to readstata13_0.8. Thanks so much!
