### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by blucap** [sjewo/readstata13#28]
I tried to install, however, I keep receiving messages that installation fails. I installed devtools as per the instruction on this site, and gfortran. But nothing helps. I run Linux mint 17.1 on a 64 bits system, R version 3.2.3 (2015-12-10)). At my older home pc it works like a charm, but not on tis new work pc.

See errors:
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [readstata13.so] Error 1
ERROR: compilation failed for package ‘readstata13’
* removing ‘/usr/local/lib/R/site-library/readstata13’

**Comment by sjewo** [comment]
You need to install `libblas-dev` and `liblapack-dev` too. Maybe an `apt-get build-dep r-base r-cran-rcpp` will get you all dependecies.

**Comment by blucap** [comment]
Yup! The library now loads, `libblas-dev` and `liblapack-dev` did the trick! Thanks.
