### ISSUE TITLE
Character Fields Importing as Numeric

### ISSUE THREAD

**Issue by skirmer** [sjewo/readstata13#30]
Hello! I am running into a problem with loading some large Stata 13 files. Long string/character fields are being converted to a long number for some reason. I tried importing the same file with readstata13 and with haven, and the attached (some values anonymized for obvious reasons) is the first five lines of each result. Any advice on how to handle it?

[stata13_example.xlsx](https://github.com/sjewo/readstata13/files/266511/stata13_example.xlsx)

**Comment by sjewo** [comment]
Hi skirmer,
just set the option ````replace.strl=TRUE```` to replace the numbers with the actual string.

**Comment by skirmer** [comment]
Ah, thank you!

**Comment by JanMarvin** [comment]
Maybe we should set it as default or check if a file contains strLs and print a message?

**Comment by sjewo** [comment]
Maybe we should change the default. It seem that replacing the strings is the expected behavior.
