### ISSUE TITLE
convert.underscore=TRUE "too aggressive"

### ISSUE THREAD

**Issue by luke-m-olson** [sjewo/readstata13#42]
Issue:
`save.dta13(test_df, "testdf.dta", convert.underscore=TRUE)` appears to convert all non-alphabetical characters in variable names to "_".  It seems that it should leave valid characters alone. This would be consistent with the help file entry: 

> convert.underscore logica. If TRUE, in variable names dots will be converted to underscores.

But seems different than the note in the NEWS file:

> convert.underscore=T will convert all non-literal characters to underscores

Here is a reproducible example:

```
test_df <- data.frame(var.1=1:3, var_2=1:3)
library(readstata13)
save.dta13("testdf.dta", convert.underscore=TRUE)

```
In Stata 14.1, the variable names are identical:  
> var__ var__

as the final 1 and 2 of each has been converted to an underscore. It seems like they should be

> var_1 var_2

*Notes*:

1. Currently using version 0.8.2. 
2. My understanding of the variable name rules for Stata are "[a-zA-Z0-9_]" (alphanumeric characters and "_") are valid characters, with the caveat that the first character cannot be numeric.

**Comment by JanMarvin** [comment]
Thanks for the report and sorry for the inconvenience. This is indeed a bug. Should have been in the release notes, this is already fixed in the latest CRAN release which contains some additional changes as well. Please update the package running `install.packages("readstata13")`. 
We check this now via a unit test, so it shall not happen again.

Marvin

**Comment by JanMarvin** [comment]
The commit that contains the fix is https://github.com/sjewo/readstata13/commit/bd1a781d9fae9f04f24e287ee4a9e5f6ce5d438a

Could you please confirm if this fixes your problem? Thanks

**Comment by luke-m-olson** [comment]
Thank you for your quick response.
That is great to hear. Unfortunately, I can't test it work, as we are "stuck" with and earlier version due to "company policies."
The commit that you sent would fix the var.1 naming issue. I wonder if it should be
names(data) <- gsub("[^a-zA-Z0-9_]", "_", names(data))
rather than
names(data) <- gsub("[^a-zA-Z0-9:]", "_", names(data))Since ":" is not in the set of valid characters.
In fact, I might be tempted to add an additional line here to make sure that the first character is not numeric:
names(data) <- gsub("[^a-zA-Z0-9_]", "_", names(data))names(data) <- sub("^[^a-zA-Z_]", "_", names(data))

**Comment by luke-m-olson** [comment]
Or even better
names(data) <- gsub("[^a-zA-Z0-9_]", "_", names(data))names(data)[grepl("^[^a-zA-Z0-9_]", names(data))] <- paste0( "_", names(data)[grepl("^[^a-zA-Z0-9_]", names(data))])
Since this version won't overwrite the first character, which might carry some information, but will instead prepend an underscore.
luke

**Comment by luke-m-olson** [comment]
My apologies for the repeated emails. The previous one had a bug in that it would add an underscore in front of all variable names.
A two line suggestion would be
names(data) <- gsub("[^a-zA-Z0-9_]", "_", names(data))names(data)[grepl("^[0-9]", names(data))] <- paste0( "_", names(data)[grepl("^[0-9]", names(data))])
luke

**Comment by JanMarvin** [comment]
No worries. I'm definitely no expert on regular expressions so we might consider additional tweaking. Will look into it tomorrow.

**Comment by JanMarvin** [comment]
@luke-m-olson Just for my understanding, I get the first line.
`names(data) <- gsub("[^a-zA-Z0-9_]", "_", names(data))` 
Though the `_` is not really needed. But I fail to understand the second.
`names(data)[grepl("^[0-9]", names(data))] <- paste0( "_", names(data)[grepl("^[0-9]", names(data))])`
To me this is a guard against variable names starting with numbers which neither R nor Stata allow. Am I missing something? Is there a way to trick Stata into writing a variable starting with a non character?

**Comment by luke-m-olson** [comment]
I guess my though was that Stata does not allow this, but R might accept numeric variable names, but then put backquotes in front of them.
Consider the following code:
temp <- data.frame("a"=1:3, ".5b"=1:3, "5"=1:3)
temp
  a X.5b X5
1 1    1  1
2 2    2  2
3 3    3  3

So the data.frame() function protects against improper names, but R will let you assign "bad" names manually.
# assign new names
names(temp) <- c("a", ".5b", "5")

temp
  a .5b 5
1 1   1 1
2 2   2 2
3 3   3 3

To reference the second and third variables of temp with the $ operator, we can use backquotes as in 

temp$`.5b`
or use [[]]
temp[[".5b"]]
I am not sure how you guys work the magic of converting the R data into .dta files, but the second line should guard against instances of the above data.frame if your conversion code does not do this already.

If I misunderstood, please let me know.

luke

**Comment by JanMarvin** [comment]
I just commited your suggested changes. Thanks

**Comment by luke-m-olson** [comment]
Great. Thank you once again for the super-quick follow up and even more for this useful piece of software.
