### ISSUE TITLE
Methods to read only the metadata of Stata files

### ISSUE THREAD

**Issue by Kevin-Jin** [sjewo/readstata13#52]
Since it may be valuable to learn of the names of the data fields or the number of rows and columns in a Stata file that is too large to read into memory, I propose either (1) implementing separate `dim.dta13()` and `colnames.dta13()` functions or (2) adding a flag to the existing `read.dta13()` function that stops it from reading the `<data>` portion of the Stata file so that a 0-row data.frame — augmented by the currently recorded attributes (e.g. `datalabel`, `time.stamp`, `formats`, etc.) plus a new `nrow` attribute — is returned to the user. With either approach, it seems easiest to just pass a flag to `read_dta()` signifying that the function should exit early.

**Comment by JanMarvin** [comment]
Hey @Kevin-Jin, what happens if you set 'select.rows =0'. Unsure if I implemented a failsafe to avoid this, but maybe we can use this as a start? Currently unavailable, but I'll look into it next week. Thanks for the idea

**Comment by Kevin-Jin** [comment]
In this case, the total number of rows in the file cannot be determined. The simplest solution may just be to return an `nrow` attribute in the function in all cases.

**Comment by JanMarvin** [comment]
I have thought about this and right now I am not gonna implement additional meta-data options. Although it might be possible that some industry people out there have datasets with insane number of variables and still want to work with R and or Stata, but right now I consider reading with `select.rows = 1` is fast enough for me to collect metadata from dta-files. In every other case we would have to obfuscate our code more and right now I do not see the relevance.
