### ISSUE TITLE
parallel importing of data

### ISSUE THREAD

**Issue by JanMarvin** [sjewo/readstata13#57]
It might be possible. Right now we read data in a single attempt:

` read first line ---> read data part -- > read last line`

For the partial reading implementation we calculate how much of a line we can skip: Our data import looks like this: 

` calculate jump size --- > read data ---> jump ---> read data ---> ...`

We could use the information how wide a row is, similar to how we skip over parts.

calculate size of a row and fetch file position where data begins

* since we know the number of cases, we can calculate the file position where to start reading from (alternative it could be total size by n)
* call function `read_data()` with position and number of rows to read (could be anything between n or 1)
* the function would return rows, these have to be combined
* once we can do that, we could spawn parallel `read_data()` processes
* in theory, we could read n-lines parallel, combine the output and return that to R

We could benefit in cases where the dta-files are huge, importing the data should not be a hard task, but it is relatively time consuming to import a file cell by cell.

**Comment by vkhodygo** [comment]
@JanMarvin  I see that this feature have been merged already. However, I don't really get how to enable it. Could you provide a few commentaries regarding this?

**Comment by vkhodygo** [comment]
@JanMarvin That's a shame. Do you have any other ideas on how to speed up reading? I noticed that my CPU is the bottleneck, however, I'm not sure where to go from this point. 
Thanks for the idea though.

**Comment by JanMarvin** [comment]
Unfortunately your best chance is to reduce the dataset to the parts you really need. Selecting specific columns or rows of the dataset can help speeding things up. Also you might look into storing it in another format or database, if you cannot keep the data in memory. Though I cannot advice a specific format. I usually try to avoid reading huge data files in R.

**Comment by JanMarvin** [comment]
As a follow up for the parallel approach. It might be possible to read the file in a stringbuf. From there it should be possible to work on chunks of a row size with openmp. But I never got it working, afaik accessing the data frame in parallel was an issue as well, and right now I have neither the time nor the need to look into it further.
