### ISSUE TITLE
Installation error on FreeBSD

### ISSUE THREAD

**Issue by bendermh** [sjewo/readstata13#62]
When readstata13 is installed on FreeBSD, following compilation error appears:

> read_data.cpp:229:9: error: use of undeclared identifier 'fseeko64'; did you mean 'fseeko'?
>         fseeko64(file, abs(type), SEEK_CUR);
>         ^~~~~~~~
>         fseeko
> /usr/include/stdio.h:352:6: note: 'fseeko' declared here
> int      fseeko(FILE *, __off_t, int);
>          ^
> 1 error generated.

**Comment by sjewo** [comment]
I added a fix in a00cc35af886dc24b4f203b42aa6dd347633caf7 
Could you try the testing branch? 
`devtools::install_github("sjewo/readstata13", ref="testing")`

**Comment by bendermh** [comment]
Hello sjewo, thank you for your fast response, I con firm you that the fixed version compiles now without error on FreeBDS.

> ** R
> ** inst
> ** tests
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> * DONE (readstata13)
