### ISSUE TITLE
add %tq date format

### ISSUE THREAD

**Issue by JanMarvin** [sjewo/readstata13#65]
A possible fix

```diff
diff --git a/R/read.R b/R/read.R
index b120e07..8926c73 100644
--- a/R/read.R
+++ b/R/read.R
@@ -341,6 +341,20 @@ read.dta13 <- function(file, convert.factors = TRUE, generate.factors=FALSE,
       z <- z - rowSums(outer(z, ls, ">="))
       as.POSIXct(z, origin = "1960-01-01")
     }
+    
+    convert_dt_q <- function(x) { 
+      z <- x / 4 
+      qrt <- z - floor(z)
+      z <- 1960 + floor(z)
+      
+      z[qrt == 0.00] <- paste0(z[qrt == 0.00], "-1-1")
+      z[qrt == 0.25] <- paste0(z[qrt == 0.25], "-4-1")
+      z[qrt == 0.50] <- paste0(z[qrt == 0.50], "-7-1")
+      z[qrt == 0.75] <- paste0(z[qrt == 0.75], "-10-1")
+      
+      z <- as.Date(z, "%Y-%m-%d")
+      z
+    }
 
     ff <- attr(data, "formats")
     ## dates <- grep("%-*d", ff)
@@ -359,6 +373,7 @@ read.dta13 <- function(file, convert.factors = TRUE, generate.factors=FALSE,
 
     for (v in grep("%tc", ff)) data[[v]] <- convert_dt_c(data[[v]])
     for (v in grep("%tC", ff)) data[[v]] <- convert_dt_C(data[[v]])
+    for (v in grep("%tq", ff)) data[[v]] <- convert_dt_q(data[[v]])
   }
 
   if (convert.factors) {
```

**Comment by JanMarvin** [comment]
closed in https://github.com/sjewo/readstata13/commit/b442419cf6c51a3fe09e3b744834303ed5b2060d

**Comment by anjoung** [comment]
Hi! I am getting the following error message when I use your package:

**Comment by JanMarvin** [comment]
Maybe due to missing values in the date file? Could you have a look @sjewo ? I'm a bit swamped with other things ATM.

**Comment by JanMarvin** [comment]
Thanks for the report @anjoung , that's not supposed to throw a warning and looks like lazy coding.

**Comment by sjewo** [comment]
> Here's a [link](https://www.dropbox.com/s/3s90yn9hmcc6n7z/temp.dta?dl=0) to a sample of the data I am working with which replicates the problem. 

The file is not public. Could give us another link?

**Comment by anjoung** [comment]
Sorry about that. Let me know if this link works: https://www.dropbox.com/s/3s90yn9hmcc6n7z/temp.dta?dl=0

**Comment by sjewo** [comment]
Thanks for the new link, @anjoung !

The warnings only occurs if NA values are present (e.g. in variable `treat_quarter`).

I'll post a fix.

**Comment by JanMarvin** [comment]
Thanks!
