### ISSUE TITLE
Fix use of fseeko64 on non-Linux platforms

### ISSUE THREAD

**Issue by brook-milligan** [sjewo/readstata13#66]
fseeko64 is not available on non-Linux platforms and there is no need for off64_t as it is not used.  Therefore, realign readstata.h to avoid compile errors.

[patch-inst_include_readstata.txt](https://github.com/sjewo/readstata13/files/3655462/patch-inst_include_readstata.txt)

**Comment by JanMarvin** [comment]
Hi @brook-milligan are our defines not enough? On which OS do you want to build? Since we build on Windows, I assume a not Linux check is not sufficient
