### ISSUE TITLE
move CI to github actions

### ISSUE THREAD

**Issue by JanMarvin** [sjewo/readstata13#71]
Travis is closing for open source projects [1] (and most likely the R support will dry out) and AppVeyor is great, but nowadays superseded by github Actions

[1] https://ropensci.org/technotes/2020/11/19/moving-away-travis/

* [x] add .github/workflows/R-CMD-check.yaml
* [x] deactivate AppVeyor (and Travis)
* [x] update README with the github badge

**Comment by JanMarvin** [comment]
A .github/workflow/*.yaml file has to be added, a slightly modified version could be copied from any of my R projects and AppVeyor support should be deactivated.

**Comment by sjewo** [comment]
Readme updated in e2b0f99f2501b330a9474edf2be1a2b1ee8cdd2f
