### ISSUE TITLE
Saving long variable names

### ISSUE THREAD

**Issue by Ales-G** [sjewo/readstata13#72]
Hello, I was wondering whether it would be possible to save long variable names using `save.dta13`I have a dataset with multiple very long variable names and using `save.dta13` they all get truncated. Is it possible to save them keeping original variable name?

```
library(readstata13)
longFun <- function(n) {
  do.call(paste0, replicate(5000, sample(LETTERS, n, TRUE), FALSE))
}

longString <- data.frame(VeryveryveryveryveryveryveryveryveryveryVeryveryveryveryveryveryveryveryveryverylongname = longFun(1), stringsAsFactors = F)
save.dta13(longString,"tst.dta")
```
After `save.dta13` I get the following warning message `Varname to long. Resizing. Max size is 32.`. Is there any possibility to keep longer varnames? Indeed, new Stata version are able to manage long variable names.

**Comment by sjewo** [comment]
Thanks for your question!

In Stata variable names have a maximum length of 32 UTF-8 characters. This is a limitation of the dta file format.

You could assign variable.labels to your data:

```
longString <- data.frame(V1 = rnorm(10), V2 = rnorm(10), stringsAsFactors = F)

# Define the labels
varlabel<- c("VeryveryveryveryveryveryveryveryveryveryVeryveryveryveryveryveryveryveryveryverylongname", "AnotherVeryveryveryveryveryveryveryveryveryveryVeryveryveryveryveryveryveryveryveryverylongname")
# Make varlabel an named vector
names(varlabel) <- names(longString)

# Assign varlabel as attribute
attr(longString, "var.labels") <- varlabel

# Save as dta file (Stata 14 allows a maximum of 80 characters for label, I set version to 15)
save.dta13(longString, "tst.dta",  version=15)
```

**Comment by Ales-G** [comment]
Dear sjewo,
thanks a lot for your prompt and kind reply! 
as far as I know, Stata has expanded the maximum length of variable names.
For instance, while `haven` does not work with very long strings (wihile `save.dta13` works well), it does implement saving of long variable names.
Take the following example: 
```
library(haven)
longString <- data.frame(VeryveryveryveryveryveryveryveryveryveryVeryveryveryveryveryveryveryveryveryverylongname = 1, stringsAsFactors = F)
write_dta(longString,"longString.dta")
```
I am able to open the `longString.dta` file and the name is displayed correctly. Is there any chance I would be able to do this with `readstata13`?

**Comment by sjewo** [comment]
Maybe Stata is able to work with longer variable names. But the Stata 16 file specification states:

> "Each name may be 1 to 32 UTF-8 characters."
  https://www.stata.com/help.cgi?dta#variablelabels
  
So I'm not sure if we we should allow longer variable names.

**Comment by Ales-G** [comment]
Thanks for clarifying this and I understand your point of view!
I wonder whether it would be worth allowing this feature as an option if it does not affect how the file works in Stata while allowing greater flexibility. 

Indeed, while you are clearly right, I am a bit puzzled because I am using a .dta file with hundred of variables longer than 32 UTF-8 characters. I am not sure how is this possible. 

As a courtesy, is there any (easy) fix, I could use in y own work with `save.dta13` to overcome the limit of 32 UTF-8? 

Thanks a lot in advance for your help

**Comment by JanMarvin** [comment]
I agree with @sjewo and believe that we have had broken variable names previously which caused trouble 
further down the road, e.g. they looked ok, but handling was somehow broken. Utf-8 32 is 128 char wide therefore stata might load longer than 32 char varnames without barking.

**Comment by Ales-G** [comment]
Dear Jan, 
thanks for your reply, just to clarify: so I should be able to correctly display variable names up to  128 char using `save.dta` or only up to 32 characters? From what I see, the truncation appears to occur at 32 character: is this correct? thanks a lot for the clarification

**Comment by JanMarvin** [comment]
@Ales-G that is correct. 32 characters should be the limit.

**Comment by Ales-G** [comment]
Yes, you are right I can shorten names, but it complicates things for me: 

1) I have been working already a bit with this data (directly importing csv into Stata). I am now running some preliminary operations in R. Changing variable names would mean go through all of the code again and change variable names whenever I have called one of the variables that I have shortened the name of. 

2) I am working with collaborators that use Stata and they are using the original variable names that are longer than 32 characters. If I am forced to shorten variable names, would mean I would have to tell them to go through their code again to make sure it runs correctly. Keeping the original long names would have been more efficient. 

In any case thanks a lot for your help. You have been super responsive.

**Comment by JanMarvin** [comment]
We would have gone with the 128 char option if it would create valid datasets, but like I said, there were some problems on the Stata side of things. Unless it's possible to create a longer than 32 characters varname in Stata, any option would create a possible issue for other users. If you absolutely need it, you should have a look for the option and disable it yourself (gut clone and build).

Personally I'd do a search and replace.
