### ISSUE TITLE
Select columns based on position (feature request)

### ISSUE THREAD

**Issue by raspatan** [sjewo/readstata13#78]
Hi there,

Would be great to be able to select columns based on index/position. I'm working with many files and the names of variables change but not their positions. So something like `read.dta13("myfile.dta",select.cols = c(1,2,4,7))` would be great. Currently it is only possible to select based on name.

There are workarounds of course (subsetting after loading), but for large files this is not optimal.

**Comment by JanMarvin** [comment]
Hi @raspatan ,
should be "easy" to implement. We calculate the position from the `selectcols` vector and the `varnames` inside the file. I'll see if I can add it over the next rainy weekend. I simply never had a use case for this.

https://github.com/sjewo/readstata13/blob/305a7f8940d5682adb9764bff99a4d741d2df596/src/read_dta.cpp#L430-L435

**Comment by JanMarvin** [comment]
Hi @raspatan ,

I've pushed https://github.com/sjewo/readstata13/commit/2fe8d9185c50608ccb8055df6e8caaf7030a8259 to our testing branch. It uses the same technique as our `select.cols` feature, but was not tested beyond the unittest I've thrown in. If you want to be an early adapter, please let me know if this solves your problem. Please be aware, that our dataset will show the variable names found for the dataset, you'd have to align them manually where needed.

(Given our "we release when we have the time and/or need to" release cycle, it might remain in testing for a bit :wink: )

```R
> # full data set
> r13 <- read.dta13("http://www.stata-press.com/data/r13/auto.dta", 
+                   convert.factors = FALSE)
> head(r13)
           make price mpg rep78 headroom trunk weight length turn displacement gear_ratio foreign
1   AMC Concord  4099  22     3      2.5    11   2930    186   40          121       3.58       0
2     AMC Pacer  4749  17     3      3.0    11   3350    173   40          258       2.53       0
3    AMC Spirit  3799  22    NA      3.0    12   2640    168   35          121       3.08       0
4 Buick Century  4816  20     3      4.5    16   3250    196   40          196       2.93       0
5 Buick Electra  7827  15     4      4.0    20   4080    222   43          350       2.41       0
6 Buick LeSabre  5788  18     3      4.0    21   3670    218   43          231       2.73       0

> # with names
> r13 <- read.dta13("http://www.stata-press.com/data/r13/auto.dta", 
+                   convert.factors = FALSE,
+                   select.cols = c("make", "price", "rep78", "weight"))
> head(r13)
           make price rep78 weight
1   AMC Concord  4099     3   2930
2     AMC Pacer  4749     3   3350
3    AMC Spirit  3799    NA   2640
4 Buick Century  4816     3   3250
5 Buick Electra  7827     4   4080
6 Buick LeSabre  5788     3   3670

> # with index positions
> r13 <- read.dta13("http://www.stata-press.com/data/r13/auto.dta", 
+                   convert.factors = FALSE,
+                   select.cols = c(1:2, 4, 7))
> head(r13)
           make price rep78 weight
1   AMC Concord  4099     3   2930
2     AMC Pacer  4749     3   3350
3    AMC Spirit  3799    NA   2640
4 Buick Century  4816     3   3250
5 Buick Electra  7827     4   4080
6 Buick LeSabre  5788     3   3670
```

Happy holidays to you

PS: I was wondering if it would be possible to mix index positioning and varnames, but ultimately decided against it. We'd have to jump through some additional loops that are currently not interesting enough for me to figure out.

**Comment by raspatan** [comment]
Amazing!! Tested and working! I asked for a second column in a one column file and the error message was "Variable "2" was not found in dta-file." You might want to edit that to indicate column index rather than variable name.

Thanks very much. Happy Christmas!

**Comment by JanMarvin** [comment]
Glad it works. Will update the message next year, it's just cosmetics after all.

What do you mean with the help options? The man pages? I have updated them too, they should work just fine. Until then you can look at https://sjewo.github.io/readstata13/ They haven't changed a lot. A few examples are in the vignette branch, which hasn't evolved a lot in the past.
