### ISSUE TITLE
Inconsistent read times

### ISSUE THREAD

**Issue by vkhodygo** [sjewo/readstata13#80]
I've been trying to improve reading times of some moderately large `.dta` files (about 5GB each), however, those times sometimes differ by an order of magnitude. The actual value is about 6 minutes (I use `tictoc` for this), however, sometimes it get stuck and I have to wait for about 2 hours to get it done  (with barely any disk activity).

Please, let me know what extra information you need in addition to this.

**Comment by JanMarvin** [comment]
Hi @vkhodygo , well there isn't really something on our end I can think of. Maybe some other process is blocking your memory or the CPU cycle or the disk. We simply read a file from the first to the last byte in sequencial order.

**Comment by vkhodygo** [comment]
This is extremely odd: I've rebooted the machine for the sake of consistency, Same files, same order, same code, read speed is somewhere around 1-2MB/s which is somewhat unacceptable.

**Comment by JanMarvin** [comment]
Could you please provide the output of `sessionInfo()`. Though I still don't think that it's us causing the slowdowns. Do you have the file on your local desktop? Is there some Antivirus running and interfering? It might as well be your station failing.
